/** Report page behaviour: mounts the Executive Shell from the embedded JSON and wires the overlay toggle. */
import { mountExecShell } from './exec-shell.js';

const data = JSON.parse(document.getElementById('report-data').textContent);
const best = data.runs.slice().sort((a, b) => b.oosSharpe - a.oosSharpe)[0];
const worst = data.runs.slice().sort((a, b) => a.dsr - b.dsr)[0];

const shell = mountExecShell({
  title: 'Algo Trading Research Kit',
  tagline: 'Three strategies backtested with transaction costs, validated walk-forward, and deflated for the number of parameter sets tried. Synthetic data; generated by CI; nothing here is a forecast or a recommendation.',
  repo: 'https://github.com/Freddricklogan/algo-trading-research-kit',
  pagesUrl: 'https://freddricklogan.github.io/algo-trading-research-kit/',
  badges: [{ label: 'Walk-forward validated', tone: 'accent' }, { label: 'Deflated Sharpe', dot: true }, { label: 'Synthetic data', dot: true }],
  kpis: [
    { label: 'Trading days', compute: () => data.days, tone: 'accent' },
    { label: 'Parameter sets tried', compute: () => data.trials },
    { label: 'Best OOS Sharpe', compute: () => `${best.name.replace('_', ' ')} ${best.oosSharpe.toFixed(2)}`, tone: 'ok' },
    { label: 'Lowest DSR', compute: () => `${worst.name.replace('_', ' ')} ${worst.dsr.toFixed(2)}`, tone: 'danger' },
    { label: 'Cost drag (best IS)', compute: () => { const r = data.runs.slice().sort((a, b) => b.inSampleSharpe - a.inSampleSharpe)[0]; return `${(r.costDrag * 100).toFixed(1)} pts`; }, tone: 'warn' }
  ],
  tour: [
    { selector: '.atr-note', title: 'What this page is', body: 'A report the CI pipeline generated by running the package on a seeded synthetic series. Every number was computed for this page; the same command reproduces it.', action: () => {} },
    { selector: `#s-${data.runs[0].name}`, title: 'In-sample looks good; that is the problem', body: 'The left chart is the best of the parameter grid on the whole series — the number a naive report shows. The dashed line is the same strategy without costs; the gap is what trading actually costs.', action: () => { const c = document.getElementById('show-nocost'); c.checked = true; c.dispatchEvent(new Event('change')); } },
    { selector: `#s-${data.runs[0].name} .atr-grid > div:last-child`, title: 'Walk-forward is the honest record', body: 'Parameters are chosen on a training window and traded on the next window, rolled forward. Only out-of-sample days are kept. Compare the out-of-sample Sharpe with the in-sample one.', action: () => {} },
    { selector: `#s-${worst.name} .atr-defl`, title: 'Deflate for the number of tries', body: `The best of N parameter sets looks good by construction. The deflated Sharpe ratio asks whether it beats what N random trials would produce. ${worst.name.replace('_', ' ')} has the lowest DSR on this run.`, action: () => {} },
    { selector: '.atr-method', title: 'Method, stated', body: 'Lag convention, cost model, fold sizes, the deflation reference and the annualisation are written down so a reader can disagree with them.', action: () => {} }
  ]
});

const toggle = document.getElementById('show-nocost');
toggle.addEventListener('change', () => {
  for (const line of document.querySelectorAll('.atr-line--nocost')) line.classList.toggle('is-hidden', !toggle.checked);
});
shell.refreshKpis();
